k

diff --git a/.config/direnv/direnvrc b/.config/direnv/direnvrc
--- a/.config/direnv/direnvrc
+++ b/.config/direnv/direnvrc
@@ -30,6 +30,32 @@ use_nvm() {
   fi
 }
 
+realpath() {
+    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
+}
+layout_python-venv() {
+    local python=${1:-python3}
+    [[ $# -gt 0 ]] && shift
+    unset PYTHONHOME
+    if [[ -n $VIRTUAL_ENV ]]; then
+        VIRTUAL_ENV=$(realpath "${VIRTUAL_ENV}")
+    else
+        local python_version
+        python_version=$("$python" -c "import platform; print(platform.python_version())")
+        if [[ -z $python_version ]]; then
+            log_error "Could not detect Python version"
+            return 1
+        fi
+        VIRTUAL_ENV=$PWD/.direnv/python-venv-$python_version
+    fi
+    export VIRTUAL_ENV
+    if [[ ! -d $VIRTUAL_ENV ]]; then
+        log_status "no venv found; creating $VIRTUAL_ENV"
+        "$python" -m venv "$VIRTUAL_ENV"
+    fi
+    PATH_add "$VIRTUAL_ENV/bin"
+}
+
 
 use_python() {
     if [ -n "$(which pyenv)" ]; then
@@ -207,7 +233,7 @@ use_ruby() {
 use_docker-machine(){
   local env=${1:-default}
   echo Docker machine: $env
-  local machine_cmd=$(docker-machine env --shell bash $env)
+  local machine_cmd=$(docker-machine env --shell zsh $env)
 
-  eval $(docker-machine env --shell bash $env)
+  eval $(docker-machine env --shell zsh $env)
 }
